config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get '/step1' => 'posts#step1'
  
  resources :posts do
   resource :likes, only:[:create, :destroy]
   end 

  resources :users, only:[:show, :index] do
    get :likes, on: :member
  end

  root 'posts#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	has_many :likes


  def liked_by?(user)
      likes.where(user_id: user.try(:id)).exists?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      # sign_upのときに、nameも許可する
      devise_parameter_sanitizer.for(:sign_up) << :name
      #  account_updateのときに、nameも許可する
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

   def create
   	@post = Post.find(params[:post_id])
   	@like = current_user.likes.build(post_id: @post.id)
   	if @like.save
   		redirect_to posts_path,notice:"いいねしました"
   	else
   	    redirect_to posts_path, alert: "いいねできませんでした"
   end
end

   def destroy
       @like = current_user.likes.find_by!(post_id: params[:post_id])
       @like.destroy
       redirect_to posts_path, notice: "お気に入りをしました"
   end    	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
 def step1
 @title ="タイトルです"
 end
 def index
  @posts = Post.all.order(created_at: :desc)
  @post = Post.new
 end
 def show
  @post = Post.find(params[:id])
 end
 def new
 	@post = Post.new
 end
 def edit
 	@post = Post.find(params[:id])
 end
 def create
 	@post = Post.new(post_params)
    @post.user_id = current_user.try(:id)
 	if @post.save
 		redirect_to '/posts', notice:"投稿できました"
 	else
 		render :new, alert: "投稿に失敗しました"
 	end
 end
 def update
 	@post = Post.find(params[:id])
 	if @post.update(post_params)
 		redirect_to post_path(@post), notice: "編集に成功しました"
 	else
 		render :edit, alert: "編集に失敗しました"
 	end
 end
 def destroy
 	@post = Post.find(params[:id])
 	@post.destroy
 	redirect_to posts_path, notice: '投稿を削除しました'
 end
  private
   def post_params
   	   params.require(:post).permit(:title, :body)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def likes
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web13Sample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %> 
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "ユーザー一覧", users_path %>
      <%= link_to "マイページ", user_path(current_user) %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>


<%= form_for(@post) do |f| %>
  <div>
   タイトル : <%= f.text_field :title  %>
  </div>
  <div>
  	本文 : <%= f.text_area :body %>
  </div>
  <div>
  	<%= f.submit "保存する" %>
  </div>

<% end %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>

<%= form_for(@post) do |f| %>
  <div>
   タイトル : <%= f.text_field :title  %>
  </div>
  <div>
  	本文 : <%= f.text_area :body %>
  </div>
  <div>
  	<%= f.submit "投稿する" %>
  </div>

<% end %>

<% @posts.each do |post| %>
<div>
<h1>
タイトル : <%= post.title %>

</div>

<div>
<% if post.liked_by?(current_user) %>
   <%= link_to "いいね解除", post_likes_path(post, method: :delete) %>
<% else %>


	<%= link_to "いいいね", post_likes_path(post),method: :post %>
<% end %>
</div>

<div>
	投稿者 : <%= post.user.try(:name) %>
</div>
<%=link_to "詳細", post_path(post)%>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_for(@post) do |f| %>
  <div>
   タイトル : <%= f.text_field :title  %>
  </div>
  <div>
  	本文 : <%= f.text_area :body %>
  </div>
  <div>
  	<%= f.submit "投稿する" %>
  </div>

<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>

<h2>タイトル : <%=@post.title  %></h2>

<div>本文 : <%= @post.body  %>
<% if user_signed_in? && @post.user_id == current_user.id %>
<span><%= link_to "削除", post_path(@post), method: :delete %></span>
<% end %>
</div>


<div>
	<% if user_signed_in? && @post.user_id == current_user.id %>

<%= link_to "編集する", edit_post_path(@post) %>
<% end %>

 | <%= link_to "一覧へ戻る", posts_path %></div>

app/views/posts/step1.html.erb
<h1>STEP1</h1>

<%= @title %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |user| %>
  <h2>
  <% if user.name.present? %>
  <%= link_to user.name, user_path(user) %>
  <% else %>
    <%= link_to '名無しさん', user_path(user) %>
    <% end %>
   </h2>
<% end %>

app/views/users/likes.html.erb
<h1>お気に入り一覧</h1>
<div>
	
  <% @user.likes.map { |l| l.post }.each do |post| %>
  <div>
  <%= post.title %> 
   <%= post.body %>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>マイページ</h2>
<%= @user.name %>
<%= link_to"#{@user.name}のお気に入り一覧" ,likes_user_path(@user) %>

名前 : <h2><%= @user.name %></h2>

<h1>投稿一覧</h1>

<% @user.posts.each do |post| %>
<div>
<h1>
タイトル : <%= post.title %>
</h1><span><%= link_to "削除", destroy_post_path(post), method: :delete %></span>
</div>

<% end %>